"""empty message

Revision ID: da088c937095
Revises: ecc7f6cfc777
Create Date: 2022-08-02 16:55:48.199125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da088c937095'
down_revision = 'ecc7f6cfc777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('image_withTag_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_images', 'image_withTag_path')
    # ### end Alembic commands ###
